import "./assets/scss/style.scss";
import lenis from "./assets/js/lenis";
import site from "./assets/js/site.js";
import aboutME from "./assets/js/about.js";
import nav from "./assets/js/nav.js";
import navMobile from "./assets/js/navMobile.js";
import script from "./assets/js/script.js";
import intro from "./assets/js/intro.js";
// import contact from "./assets/js/contact.js";
// import p55 from "./assets/js/p55.js";

lenis();
site();
script();
aboutME();
navMobile();
intro();
// contact();
nav();
// p55();
